# Generated by Django 3.2.6 on 2021-09-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_fellow', models.CharField(max_length=5000, null=True, verbose_name='Full name of Fellow')),
                ('year_of_completion_of_ICOHRTA_feliowship_degree_programme', models.CharField(max_length=5000, null=True, verbose_name='Year of Completion of ICOHRTA Feliowship Degree Programme')),
                ('year_of_completion_of_ICOHRTA_feliowship_degree_programme_institution', models.CharField(max_length=5000, null=True, verbose_name='Instituion where you did your ICOHRTA Feliowship Degree Programme')),
                ('position_s_held_since_completion_of_degree_programme1', models.CharField(max_length=5000, null=True)),
                ('position_held_since_completion_of_degree_programme_institution', models.CharField(max_length=5000, null=True, verbose_name='Institution name where you are currently working')),
                ('current_position', models.CharField(max_length=5000, null=True)),
                ('current_position_institution', models.CharField(max_length=5000, null=True)),
                ('scientific_publications_1', models.CharField(max_length=5000, null=True)),
                ('grants_applied_for_1', models.CharField(max_length=5000, null=True)),
                ('award_number_or_sponsor_1', models.CharField(max_length=5000, null=True)),
                ('project_period_start_1', models.CharField(max_length=5000, null=True)),
                ('project_period_end_1', models.CharField(max_length=5000, null=True)),
                ('pd_or_pi_1', models.CharField(max_length=5000, null=True)),
                ('number_of_trainees_supported_1', models.IntegerField(null=True)),
                ('mentors_1', models.CharField(max_length=5000, null=True)),
                ('mentees_1', models.CharField(max_length=5000, null=True)),
                ('any_other_relevant_information', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='currentposition',
            name='name_of_fellow',
        ),
        migrations.RemoveField(
            model_name='grantsappliedfor',
            name='name_of_fellow',
        ),
        migrations.RemoveField(
            model_name='grantsawarded',
            name='name_of_fellow',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='name_of_fellow',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='name_of_fellow',
        ),
        migrations.RemoveField(
            model_name='positionsheld',
            name='name_of_fellow',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='name_of_fellow',
        ),
        migrations.RemoveField(
            model_name='relevant_information',
            name='name_of_fellow',
        ),
        migrations.AlterField(
            model_name='nameinstitution',
            name='name_of_fellow',
            field=models.CharField(max_length=5000, null=True, verbose_name='Full name of Fellow'),
        ),
    ]
