# Generated by Django 3.2.6 on 2021-09-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210906_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevant_information',
            name='any_other_relevant_information',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
